version: "3.9"
services:
  remote-photographer-message-broker:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
      
  remote-photographer-service:
    image: loremdonecipsum/remote-photographer:alpha
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - message.broker-service:parameters:host=localhost
      - message.broker-service:parameters:username=guest
      - message.broker-service:parameters:password=guest
      - message.broker-service:parameters:receive.endpoint=RemotePhotographer
    ports:
      - 8080:8080