name: build

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
      architecture:
        required: true
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true
    
jobs:
  build_service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: restore dependencies
      run: dotnet restore ./src/RemotePhotographer.sln -r ${{ inputs.architecture }}

    - name: build service
      run: dotnet build ./src/RemotePhotographer.sln -a ${{ inputs.architecture }} -c ${{ inputs.configuration }} --no-restore -o out

    - name: login to docker hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_password }}

    - name: copy dockerfile
      run: cp ./src/RemotePhotographer/Dockerfile ./Dockerfile

    - name: list files
      run: ls -l

    - name: build and publish image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: loremdonecipsum/remote-photographer:${{ inputs.architecture }}-alpha