name: publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "src/RemotePhotographer/**.*"
      - "src/Boilerplate/**.*"
jobs:

  linux_arm:
    uses: loremipsumdonec/remote-photographer/.github/workflows/build.yml@master
    with:
      configuration: Release
      architecture: linux-arm
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  linux_x64:
    uses: loremipsumdonec/remote-photographer/.github/workflows/build.yml@master
    with:
      configuration: Release
      architecture: linux-x64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      

    