name: publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "src/RemotePhotographer/**.*"
      - "src/Boilerplate/**.*"
jobs:

  linux_arm:
    uses: loremipsumdonec/remote-photographer/.github/workflows/build.yml@master
    with:
      configuration: Release
      architecture: arm
      platform: linux/arm
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  linux_x64:
    uses: loremipsumdonec/remote-photographer/.github/workflows/build.yml@master
    with:
      configuration: Release
      architecture: x64
      platform: linux/amd64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  manifest:
    needs: [linux_arm, linux_x64]
    runs-on: ubuntu-latest

    steps: 

    - name: login to docker hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_password }}

    - name: build manifest
      run: | 
        docker manifest create loremdonecipsum/remote-photographer:alpha \ --amend loremdonecipsum/remote-photographer:x64-alpha --amend loremdonecipsum/remote-photographer:arm-alpha
        docker manifest push loremdonecipsum/remote-photographer:alpha
