name: publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "src/RemotePhotographer/**.*"
      - "src/Boilerplate/**.*"
jobs:

  lorem:
    uses: loremipsumdonec/remote-photographer/.github/workflows/build.yml@main
    with:
      configuration: Release

    